### ISSUE TITLE
where to download the MST dataset

### ISSUE THREAD

**Issue by nikparth** [patrickmineault/your-head-is-there-to-move-you-around#1]
Hi - im looking to compare some models with the DorsalNet on predicting the MST data, but it seems you've only provided the preprocessing scripts and not the download of the original data? I tried to look for it, but could not find the link so could you let me know if this data is available somewhere? 

Thanks!

**Comment by patrickmineault** [comment]
Hi @nikparth, send me an email and I'll send you a Drive link: patrick.mineault@gmail.com
